# Generated by Django 3.0.6 on 2020-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201102_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.ImageField(upload_to='Users/deepakg/PycharmProjects/TaskManagement/uploads'),
        ),
    ]
