# Generated by Django 3.0.6 on 2020-11-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20201106_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assignee',
        ),
    ]
